options:
    repository:
        description: APT Repository to use for installing Landscape.
        type: string
    license-file:
        description: License file for LDS
        type: string
    services:
        description: |
            Landscape services listed as space-separated entries.  Valid
            services are: appserver, msgserver, pingserver, combo-loader,
            async-frontend, apiserver, package-upload, package-search, cron,
            juju-sync and static.  This field is effecitvely immutable.  If
            not set before the charm is installed, changes to it will be
            ignored.
        type: string
    service-count:
        type: string
        default: AUTO
        description: |
            Many landscape services can have multiple copies started up.  By
            altering this setting, you can increase the launch count.  A
            numeric value will tell all capable landscape services on this juju
            unit to spawn that number of multiple copies.  Leave at the default
            of "AUTO", to let the charm determine the optimum number of
            services given the discovered properties of the box (RAM, disk
            space, cpu).  You can also supply a syntax of:
            "<service-name>:<number> <service-name>:<number>" as a value, to
            control the launch of individual services.  Services that cannot
            "scale" in this way will politely ignore these settings.

