options:
    source:
        default: ppa:landscape/14.10
        type: string
        description: |
            APT repository to use for installing Landscape.
    key:
        default:
        type: string
        description: |
            Key ID to import to the apt keyring to support use with arbitary source
            configuration from outside of Launchpad archives or PPA's.
    license-file:
        description: License file for LDS.
        type: string
        default:
    admin-name:
        description: |
            Name of the account administrator. If this, admin-email and
            admin-password are specified, then the standalone account will be
            created as part of the deployment, and this person will be its
            administrator. If not specified, Landscape will prompt for these
            details when it is first accessed with a web browser. Has no
            effect if changed after a deployment.
        type: string
        default:
    admin-email:
        description: |
            Email of the account administrator. To have any effect, needs to
            specified in conjunction with admin-name and admin-password. Has
            no effect if changed after a deployment.
        type: string
        default:
    admin-password:
        description: |
            Password of the account administrator. To have any effect, needs
            to be specified in conjunction with admin-name and admin-email.
            Has no effect if changed after a deployment.
        type: string
        default:
