options:
    source:
        default: "ppa:landscape/15.10"
        type: string
        description: |
            The source from which to install the landscape packages. Possible
            values are:
                - A full deb line: "deb http://ppa.launchpad.net/landscape/15.10/ubuntu trusty main"
                - A PPA URL: "ppa:landscape/15.10"
                - A version number: "15.10"
    key:
        default:
        type: string
        description: |
            Key ID to import to the apt keyring to support use with arbitary source
            configuration from outside of Launchpad archives or PPA's.
    license-file:
        description: |
            License file for LDS, either as a base64-encoded string containing
            the actual license file data, or a file://, http:// or https:// URL
            pointing to the license file for download.
        type: string
        default:
    openid-provider-url:
        default:
        type: string
        description: |
            OpenID provider URL to use for authentication to Landscape.
    openid-logout-url:
        default:
        type: string
        description: |
            OpenID provider URL to use to log out of Landscape.
    root-url:
        description: |
            The root URL for this landscape deployment. If left blank the public
            IP of the first related HAproxy unit will be used instead.
        type: string
        default: ""
    ssl-cert:
        type: string
        description: |
            base64 encoded SSL certificate to use for the Landscape server.
            It will be passed verbatim to the haproxy charm. If not set, a
            self-signed certificated will be used instead.
        default: ""
    ssl-key:
        type: string
        description: |
            base64 encoded private key for the default SSL certificate. If
            ssl_cert is not set, this will be ignored.
        default: ""
