options:
    source:
        default: ppa:landscape/14.10
        type: string
        description: |
            APT repository to use for installing Landscape.
    key:
        default:
        type: string
        description: |
            Key ID to import to the apt keyring to support use with arbitary source
            configuration from outside of Launchpad archives or PPA's.
    license-file:
        description: License file for LDS.
        type: string
        default:
    openid-provider-url:
        default:
        type: string
        description: |
            OpenID provider URL to use for authentication to Landscape.
    openid-logout-url:
        default:
        type: string
        description: |
            OpenID provider URL to use to log out of Landscape.
    admin-name:
        description: |
            Name of the account administrator. If this, admin-email and
            admin-password are specified, then the standalone account will be
            created as part of the deployment, and this person will be its
            administrator. If not specified, Landscape will prompt for these
            details when it is first accessed with a web browser. Has no
            effect if changed after a deployment.
        type: string
        default:
    admin-email:
        description: |
            Email of the account administrator. To have any effect, needs to
            specified in conjunction with admin-name and admin-password. Has
            no effect if changed after a deployment.
        type: string
        default:
    admin-password:
        description: |
            Password of the account administrator. To have any effect, needs
            to be specified in conjunction with admin-name and admin-email.
            Has no effect if changed after a deployment.
        type: string
        default:
    root-url:
        description: |
            The root URL for this landscape deployment. If left blank the public
            IP of the first related HAproxy unit will be used instead.
        type: string
        default: ""
    ssl-cert:
        type: string
        description: |
            base64 encoded SSL certificate to use for the Landscape server.
            It will be passed verbatim to the haproxy charm. If not set, a
            self-signed certificated will be used instead.
        default: ""
    ssl-key:
        type: string
        description: |
            base64 encoded private key for the default SSL certificate. If
            ssl_cert is not set, this will be ignored.
        default: ""
