_common:
    services:
        rabbitmq-server:
            charm: cs:trusty/rabbitmq-server-4
        postgresql:
            charm: cs:trusty/postgresql-3
            constraints: mem=2048
            options:
                extra-packages: python-apt postgresql-contrib postgresql-.*-debversion
                max_connections: 500
        haproxy:
            charm: cs:precise/haproxy-32
            options:
                enable_monitoring: True
                monitoring_allowed_cidr: "0.0.0.0/0"
                monitoring_password: "haproxy"
                default_timeouts: "queue 60000, connect 5000, client 120000, server 120000"
                # Don't deploy default haproxy service on port 80
                services: ""
        apache2:
            charm: cs:trusty/apache2-4
            expose: True
            options:
                enable_modules: proxy proxy_http proxy_balancer rewrite expires headers ssl
                ssl_cert: SELFSIGNED
                ssl_certlocation: apache2.cert
                ssl_keylocation: apache2.key

landscape:
    inherits: _common
    series: trusty
    services:
        landscape:
            branch: lp:~landscape/landscape-charm/stable
            constraints: mem=2048
            options:
                service-count: "2"
                landscape-password: "look-a-different-password"
                services: static appserver pingserver combo-loader async-frontend apiserver package-upload jobhandler package-search cron juju-sync
                repository: include-file://repo-file
                license-file: include-file://license-file
        landscape-msg:
            branch: lp:~landscape/landscape-charm/stable
            charm: landscape
            constraints: mem=2048
            options:
                landscape-password: "look-a-different-password"
                services: msgserver
                repository: include-file://repo-file
                license-file: include-file://license-file
    relations:
        - [landscape, rabbitmq-server]
        - [landscape, haproxy]
        - ["landscape:vhost-config", "apache2:vhost-config"]
        - ["landscape:db-admin", "postgresql:db-admin"]
        - ["haproxy:website", "apache2:reverseproxy"]
        - [landscape-msg, rabbitmq-server]
        - [landscape-msg, haproxy]
        - ["landscape-msg:db-admin", "postgresql:db-admin"]

landscape-dense:
    inherits: landscape-dense-maas
    services:
        apache2:
            to: 0

landscape-dense-maas:
    inherits: landscape
    services:
        landscape:
            to: lxc:0
        landscape-msg:
            to: lxc:0
        postgresql:
            to: lxc:0
        rabbitmq-server:
            to: lxc:0
        apache2:
            to: lxc:0
        haproxy:
            to: lxc:0

